### ISSUE TITLE
Failure in aes.rb on Ubuntu 16/18 when using auth_proto=SHA and priv_proto=AES

### ISSUE THREAD

**Issue by stideswell** [swisscom/ruby-netsnmp#20]
Forgive me as I am a total Ruby newbie!

Using code like the following ...
_snmp = NETSNMP::Client.new(host: '127.0.0.1', port: 161, version: 3,
                           username: user, auth_protocol: auth_proto, auth_password: auth_pass,
                           priv_protocol: priv_proto, priv_password: priv_pass)_

I get the following error ...
Traceback (most recent call last):
	9: from ./test.rb:13:in `<main>'
	8: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/client.rb:56:in `get'
	7: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/client.rb:144:in `handle_retries'
	6: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/client.rb:56:in `block in get'
	5: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/v3_session.rb:23:in `send'
	4: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/session.rb:41:in `send'
	3: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/v3_session.rb:76:in `decode'
	2: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/message.rb:34:in `decode'
	1: from /var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/security_parameters.rb:89:in `decode'
/var/lib/gems/2.5.0/gems/netsnmp-0.1.4/lib/netsnmp/encryption/aes.rb:38:in `decrypt': invalid encrypted PDU received (NETSNMP::Error)

If I make the following edits to **aes.rb** ...
_def decrypt(encrypted_data, salt:, engine_boots:, engine_time:)
        raise Error, "invalid priv salt received" unless (salt.length % 8).zero?
        p "Encrypted data = #{encrypted_data}"
        p "Encrypted data length = #{encrypted_data.length}"
        p "Encrypted data length mod8 = #{encrypted_data.length % 8}"
        p "Encrypted data length mod8 is zero = #{(encrypted_data.length % 8).zero?}"
        p "Does Integer have a 'zero?=' method? = #{(encrypted_data.length % 8).methods.include? 'zero?='.to_sym }"
        p "Does Integer have a 'zero?' method? = #{(encrypted_data.length % 8).methods.include? 'zero?'.to_sym }"
        #raise Error, "invalid encrypted PDU received" unless (encrypted_data.length % 8).zero?_

Then everything appears to work just fine and it produces the following output ...
_"Encrypted data = \x96\x16$\xBB}\x9C ---SNIP TO OBSCURE--- \xE7\xEF\xC8I\x17\xC4"
"Encrypted data length = 77"
"Encrypted data length mod8 = 5"
"Encrypted data length mod8 is zero = false"
"Does Integer have a 'zero?=' method? = false"
"Does Integer have a 'zero?' method? = true"_

So the root cause of the failure is the absence of method zero?= on my host, but also my encrypted data does not divide through by zero.

ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]

gem list  | grep netsnmp
netsnmp (0.1.4)

**Comment by HoneyryderChuck** [comment]
@stideswell can you run your example against the master branch? I guess this has been solved [here](https://github.com/swisscom/ruby-netsnmp/pull/17).

**Comment by stideswell** [comment]
Thanks Tiago

Yes that would definitely work as it's the same fix (remarking out the modulo 8 check line) as I found to work for me. I realise that this project has now forked to net-snmp2 (https://github.com/jbreeden/net-snmp2), but will try another question on this project in a moment as I'm struggling to get net-snmp2 to work at all well.

**Comment by HoneyryderChuck** [comment]
This is not the same project as net-snmp2. But I'm glad it worked for you. Will make a release soon.
