### ISSUE TITLE
Counter32 values are way off

### ISSUE THREAD

**Issue by stideswell** [swisscom/ruby-netsnmp#21]
Hello

ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]

gem list | grep netsnmp
netsnmp (0.1.4)

This is on Ubuntu 16 and 18.

If I walk the following OID, 1.3.6.1.4.1.2021.11, using snmpwalk ...
_iso.3.6.1.4.1.2021.11.1.0 = INTEGER: 1
iso.3.6.1.4.1.2021.11.2.0 = STRING: "systemStats"
--snip--
iso.3.6.1.4.1.2021.11.11.0 = INTEGER: 99
iso.3.6.1.4.1.2021.11.50.0 = Counter32: 389775
iso.3.6.1.4.1.2021.11.51.0 = Counter32: 144655
iso.3.6.1.4.1.2021.11.52.0 = Counter32: 167738
iso.3.6.1.4.1.2021.11.53.0 = Counter32: 50723103
iso.3.6.1.4.1.2021.11.54.0 = Counter32: 60808
--snip--_

You can see that, e.g., .53.0, "CPU idle" is ~50 million. But using netsnmp I get the following ...
_1.3.6.1.4.1.2021.11.1.0 = 1
1.3.6.1.4.1.2021.11.2.0 = systemStats
--snip--
1.3.6.1.4.1.2021.11.11.0 = 98
1.3.6.1.4.1.2021.11.50.0 = 1522
1.3.6.1.4.1.2021.11.51.0 = 565
1.3.6.1.4.1.2021.11.52.0 = 655
1.3.6.1.4.1.2021.11.53.0 = 773
1.3.6.1.4.1.2021.11.54.0 = 237
--snip--_

So the values are out by a factor of ~65k. I could just multiply through  by 65535 (or << 16) for each value I find, but that seems a bit dubious to me? Why are the values I'm getting via netsnmp so far out? Is the correct approach to multiply by 65k? If so, why is this not documented in the wiki? Am I doing something wrong?

Thanks, Simon.

**Comment by HoneyryderChuck** [comment]
Go Simon, Thx for the report. It is indeed a bug. Counter32 is a badly supported application type. Will see about implementing a fix based on your example.

**Comment by HoneyryderChuck** [comment]
@stideswell  could you retry your example with the master branch?

**Comment by stideswell** [comment]
Thanks Tiago, that worked. Simon

**Comment by HoneyryderChuck** [comment]
Great! Will close this and hack a release soon.
