### ISSUE TITLE
Certain gauge / counter32 values are being encoded incorrectly

### ISSUE THREAD

**Issue by jrgns** [swisscom/ruby-netsnmp#27]
We ran across this when we needed to set a gauge type. Some values would work (0 to 127, and 256 and up), but some values won't work (128 to 255).

The command we used was (excute the obviously bogus OID)

```
manager.set(oid: '1.2.3', value: 255, type: :gauge)
```

Bitwise, the difference between the values are

* 0 to 127 got padded to a byte, which always started with a zero (0000 0000 to 0111 1111)
* 128 to 255 were also a byte, but doesn't start with a zero (1000 0000 to 1111 1111)
* 256 and above were padded to two bytes, and didn't start with a zero (0000 0001 0000 0000 to 0111 1111 1111 1111)

It looks like ASN encoding requires a leading zero:

```
OpenSSL::ASN1::Integer.new(127).to_der
=> "\x02\x01\x7F"
OpenSSL::ASN1::Integer.new(128).to_der
=> "\x02\x02\x00\x80
```

Notice the extra byte added to 128 - 1000 0000 is encoded as 0000 0000 1000 0000

On [this line](https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/varbind.rb#L88) the code removes empty bytes for gauges (and close to that also counters), and then wraps the value in `OpenSSL::ASN1::ASN1Data`.

I believe the fix is to either add a check in line 81 to ensure that the bytes always have leading zero, or to use `OpenSSL::ASN1::Integer` instead of `OpenSSL::ASN1::ASN1Data`

**Comment by HoneyryderChuck** [comment]
Thx for the report!

First, which version are you on? Because line 81 is [this line](https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/varbind.rb#L81), so I'm not sure whether that has to do with the gauge.

Do you have some documentation on how to act upon gauge numbers? I'm handling them exactly like counter32 numbers, as all info I found led me to believe they are handled the same.

Maybe the first step would be for you to submit a PR and add tests setting proper expectations for your edge cases (the 127, 128, 255 and 256 examples seem to be a good fit).

After that, we'll consider possible solutions. The way I see it, just using ASN1 Integers is not an option, as gauge is an application type.

**Comment by jrgns** [comment]
@HoneyryderChuck Sorry, it's [line 88](https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/varbind.rb#L88). You'll see it's the same for gauge and counter.

Unfortunately I don't have documentation. From what I've read, though, gauges and counters are just integers with specific ranges.So even through you're handling the gauges and counters the same, you're not handling it the same way you would a [raw integer](https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/varbind.rb#L32).

I'd be happy to add failing specs. I first wanted to know what the reasoning was behind handling gauges / counters differently than integers?

**Comment by jrgns** [comment]
@HoneyryderChuck I forgot to mention, we tested this using standard snmp tools, too, so it's definitely the ruby snmp library and not the device we're testing against.

**Comment by HoneyryderChuck** [comment]
So, if I understand correctly, both gauges and counter32 handling are incorrect?

> I'd be happy to add failing specs. I first wanted to know what the reasoning was behind handling gauges / counters differently than integers?

Thx, will be looking forward to see them. There was no particular reasoning beyond making it work for my use case, but maybe I should have tested them further. Again, thx for the report!

**Comment by jrgns** [comment]
> So, if I understand correctly, both gauges and counter32 handling are incorrect?

@HoneyryderChuck I haven't confirmed it, but if SNMP is consistent (!) that might be the case.

**Comment by jrgns** [comment]
@HoneyryderChuck I'll be creating the specs for this soon.

The issue boils down to the fact that a [gauge is unsigned, and a counter is signed](http://cuddletech.com/articles/snmp/node9.html). So for the gauge the first bit specifies if it's positive (bit0 = 0) or negative (bit0 = 1). So handling a gauge and a counter in the same way won't work.

**Comment by jrgns** [comment]
@HoneyryderChuck FYI, still a WIP, but this is the direction I'm going in: https://github.com/automation-exchange/ruby-netsnmp/commit/cf2c4d56cbca127e6a127bd267843585c223d856

**Comment by HoneyryderChuck** [comment]
LGTM 👍  looking forward to the PR :)

**Comment by jrgns** [comment]
@HoneyryderChuck I've added the failing specs. Please check if you agree with the checks. The first one fails outright in that -1 isn't returned as -1, the second one fails on the bit check.

If you're happy with the specs, I'll start looking at the fix.

**Comment by HoneyryderChuck** [comment]
0.1.7 published! Thx for your work, and again sorry for the delay.

**Comment by jrgns** [comment]
@HoneyryderChuck Woot woot! No worries, thanx :)
