### ISSUE TITLE
HMAC-SHA-2 Authentication Protocols in the User-based Security Model (USM) for SNMPv3

### ISSUE THREAD

**Issue by fwininger** [swisscom/ruby-netsnmp#29]
How you plan the support of SHA-2 for SNMPv3 ?

https://tools.ietf.org/html/rfc7630

**Comment by HoneyryderChuck** [comment]
I actually had never heard about the rfc. I'm open to contributions for extending the authentication functionality, definitely.

**Comment by fwininger** [comment]
@jinxka can you propose a PR for this issue ?
