### ISSUE TITLE
SNMPSet two different OIDs in one request command?

### ISSUE THREAD

**Issue by stuarthannig** [swisscom/ruby-netsnmp#34]
Forgive my ignorance with SNMPv3, is this gem able to use SNMP Set with two OIDs in a command?

Use case, I am trying to save the config file on a network switch device `snAgWriteNVRAM 1.3.6.1.4.1.1991.1.1.2.1.3.0` after enabling/disabling an interface port. The OID to save the config file requires an additional OID for  `snAgGblPassword 1.3.6.1.4.1.1991.1.1.2.1.15.0` (System Security Access Password).

My successful SNMPSet command on CLI with two OIDs look like this:

```
snmpset -v 3 -u <username> -l authPriv -a <auth_protocol:> -A <auth_password> -x <priv_protocol> -X priv_password -t 3 <host> 1.3.6.1.4.1.1991.1.1.2.1.15.0 s <snAgGblPassword> 1.3.6.1.4.1.1991.1.1.2.1.3.0 i 3

# For readability, the above looks like this
snmpset 
  -v 3
  -u <username>
  -l authPriv
  -a <auth_protocol:> -A <auth_password>
  -x <priv_protocol> -X <priv_password>
  -t 3 <host>
  1.3.6.1.4.1.1991.1.1.2.1.15.0 s <snAgGblPassword>
  1.3.6.1.4.1.1991.1.1.2.1.3.0 i 3
``` 

The SNMPSet command will fail without the accompanying `snAgGblPassword` OID being set BEFORE the `snAgWriteNVRAM` OID. So order matters as well.

**Comment by HoneyryderChuck** [comment]
Hi, are you sure that's not syntactic sugar for 2 set commands? Maybe if you run that command in verbose mode you can confirm.

**Comment by stuarthannig** [comment]
That's what I was hoping, but I do not believe so. See below.

```
~$ snmpset -v 3 [...] 1.3.6.1.4.1.1991.1.1.2.1.15.0 s <snAgGblPassword>
iso.3.6.1.4.1.1991.1.1.2.1.15.0 = STRING: "<snAgGblPassword>"
~$ snmpset [...] 1.3.6.1.4.1.1991.1.1.2.1.3.0 i 3
Error in packet.
Reason: undoFailed
Failed object: iso.3.6.1.4.1.1991.1.1.2.1.3.0
```

**Comment by stuarthannig** [comment]
Just to verify, what I think I am looking to do is:

```
manager.set(
  { oid: "1.3.6.1.4.1.1991.1.1.2.1.15.0", value: "<snAgGblPassword>" },
  { oid: "1.3.6.1.4.1.1991.1.1.2.1.3.0", value: 3 }
)
```

But that is unsupported at the moment?

**Comment by stuarthannig** [comment]
Actually, I got it working. Not sure where I was missing up before when I last triedand was failing. But this is supported. Thank you for your patience.

```
[43] pry(main)> manager.set(
[43] pry(main)*   { oid: "1.3.6.1.4.1.1991.1.1.2.1.15.0", value: "<snAgGblPassword>" },
[43] pry(main)*   { oid: "1.3.6.1.4.1.1991.1.1.2.1.3.0", value: 3 }
[43] pry(main)* )
=> ["<snAgGblPassword>", 3]
```

**Comment by stuarthannig** [comment]
Ok, I think I know where I messed up. I was initially passing the multiple OIDs as an array `.set [{oid: ...}, {oid: ...}]` instead of sending as a splat `.set {oid: ...}, {oid: ...}`. The latter works.

**Comment by HoneyryderChuck** [comment]
It's actually the first time someone uses it that ay, glad it was already working.
