### ISSUE TITLE
Bug AES decrypt when salt is empty

### ISSUE THREAD

**Issue by jinxka** [swisscom/ruby-netsnmp#42]
Hello,

I had a case when one of my device returned an empty salt (""), and I got the error 'iv must be 16 bytes'

After investigating, I found that we verify if the salt is '% 8' but not if it's present.

*(''.length % 8).zero?* is true, it should not.

https://github.com/swisscom/ruby-netsnmp/blob/9d47f0b7220898ba3bc7054d854a459296ade22a/lib/netsnmp/encryption/aes.rb#L31

**Comment by HoneyryderChuck** [comment]
Hi @jinxka , thank you for the report!

I've opened an MR with a fix, could you see if that fixes the issue?
