### ISSUE TITLE
TSM Support

### ISSUE THREAD

**Issue by yevgeniypopov** [swisscom/ruby-netsnmp#5]
Hi, is there any plans to support Transport Security Model?
http://net-snmp.sourceforge.net/wiki/index.php/TSM

**Comment by HoneyryderChuck** [comment]
Thank you for the message.

It's the first I hear about TSM. I will have a look at the RFC, but this should be possible already by using the :proxy argument (where you pass your SSH or TLS IO object), provided there is no handshake.

Do you have any available script to test this?

**Comment by yevgeniypopov** [comment]
> this should be possible already by using the :proxy argument (where you pass your SSH or TLS IO object)

I will try it, thanks

> Do you have any available script to test this?

not yet, but I will try to come up with something.

**Comment by HoneyryderChuck** [comment]
Let me know how your experiments went, the idea of the :proxy argument was to support such cases, but it might be insufficient for some (and is definitely untested for non-udp proxies).

In the case that you might consider a PR, let me know. The testing environment is as of yet dependent on docker, but I'm working on lowering the barrier of entry, if this is in an impediment for you, I might prioritize this task.

**Comment by stakach** [comment]
I've used the proxy to support evented IO in https://github.com/cotag/libuv
With this code: https://github.com/acaprojects/ruby-engine/blob/master/lib/protocols/snmp.rb
Specifically for use in: https://developer.acaprojects.com/#/driver-development/utilities-and-helpers?id=snmp

Works well!

**Comment by HoneyryderChuck** [comment]
@stakach great to hear! I actually designed that API to work well with Celluloid::IO, cool that it works with other evented engines. Are you also using any secure transport?

**Comment by stakach** [comment]
I'm not using netSNMP with a secure transport however it would be trivial with Libuv or Eventmachine using https://github.com/igrigorik/em-synchrony

I haven't cracked DTLS support in libuv yet

**Comment by HoneyryderChuck** [comment]
@yevgeniypopov will close the ticket, as I assume that this should not be an issue using the `:proxy` option. Feel free to reopen or open a new one whenever you get to try it.
