### ISSUE TITLE
The gem does not recognize authentication failures

### ISSUE THREAD

**Issue by jinxka** [swisscom/ruby-netsnmp#50]
Hello,

As you can read in the title, it looks like the gem does not recognize the authentication failures.

When using bad passwords, I was expecting the client to raise an error 'Authentication failure', like it does on the snmpget command:

![image](https://user-images.githubusercontent.com/11526533/120662843-c2a3a400-c489-11eb-9fba-c77cc2961ddc.png)

But instead of raising an error, it returns an integer which correspond to the number of requests received by the device.

Is it voluntary?

**Comment by HoneyryderChuck** [comment]
Hi,

> Is it voluntary?

Definitely not. It's possible I overlooked it when I implemented it.

Could you patch it? I imagine this would be relatively easy to contribute, given that [the test suite already relies on authentication credentials](https://github.com/swisscom/ruby-netsnmp/blob/master/spec/client_spec.rb#L183-L202), so you just have to add a test with wrong credentials annd see an exception pop out.

**Comment by HoneyryderChuck** [comment]
@jinxka had to patch your changes, as some things were missing. I've released `v0.4.2`, let me know if it all works as intended.
