### ISSUE TITLE
walk method does not work

### ISSUE THREAD

**Issue by NetForces** [swisscom/ruby-netsnmp#8]
Trying to get the list of SSIDs on a Ruckus ZoneDirector. Using shell snmpwalk commands works as expected:

```
#   $ snmpwalk -On -v3  -l authPriv -u "my_user" -a MD5 -A "my_pass"  -x DES -X "my_pass" 192.168.161.202 .1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2
#   .1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2.1 = STRING: "MYSSID1"
#   .1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2.2 = STRING: "MYSSID2"
```

Trying the following code returns nothing:

```
require 'netsnmp'

# example you can test against the docker simulator provided. port attribute might be different. 
manager = NETSNMP::Client.new(host: "192.168.161.202", port: 161, username: "my_user",
                              auth_password: "my_pass", auth_protocol: :md5, 
                              priv_password: "my_pass", priv_protocol: :des,
                              timeout: 30, version: "v3")

manager.walk(oid: ".1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2") do |oid_code, value| 
  puts "for #{oid_code}: #{value}"
end
```

Using a more "manual" method to get the data works:

```
require 'netsnmp'

# example you can test against the docker simulator provided. port attribute might be different. 
manager = NETSNMP::Client.new(host: "192.168.161.202", port: 161, username: "my_user",
                              auth_password: "my_pass", auth_protocol: :md5, 
                              priv_password: "my_pass", priv_protocol: :des,
                              timeout: 30, version: "v3")

count=1
loop do 
  value = manager.get(oid: ".1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2.#{count}")
  break if value == 0
  puts "SSID #{count}: #{value}"
  count = count + 1
end 
```

Running ruby v2.3.1p112 with the netsnmp gem v0.1.3

**Comment by HoneyryderChuck** [comment]
I had a debug mode planned exactly to debug such cases...

Do you know your way around ruby well? I'd suggest to use a debugger like `byebug` to inspect the PDUs sent. The relevant code for `#walk` is [here](https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/client.rb#L77-L100), and you can see what it does. In fact, walk feature is not part of the spec, it's just (loosely) based on the `snmpwalk` cli tool.

As you can see, it's a sequence of `GETNEXT` PDUs. I'd try to reproduce your success case using those. If you manage to find the cause, PRs are welcome :)

**Comment by HoneyryderChuck** [comment]
After another look... can you try replace this line?

```ruby
- manager.walk(oid: ".1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2") do |oid_code, value| 
+ manager.walk(oid: ".1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2").each do |oid_code, value| 
```

If this works for you, please remind me to update the README (I guess you copy pasted it from there).

**Comment by NetForces** [comment]
Nope same thing with:

```
manager.walk(oid: ".1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2").each do |oid_code, value|  
  puts "for #{oid_code}: #{value}"
end
```

No output.

If I do:

```
my_walk = manager.walk(oid: ".1.3.6.1.4.1.25053.1.2.2.2.1.1.1.1.2")
puts my_walk.inspect
```

I get:

```
#<Enumerator: #<Enumerator::Generator:0x0000000070b7f0>:each>
```

I'll check with `byebug` later on today.

**Comment by NetForces** [comment]
@HoneyryderChuck all yours. Just documentation change. Also needed to provide the OID without the leading `.`. `snmpwalk` accepts it with it, but that's ok for me as is.

cc @mdeloupy
